OffsetOf Fixes
leoetlino/project-restoration pull request #190
Opened 2021-07-29 18:25 UTC by PhlexPlexico

Just recently updated my 3dstools and libctru to see that the implemented OffsetOf no longer works.

```
"/mnt/c/Users/phlex/Projects/project-restoration/source/./game/context.h:358:63: error: non-constant condition for static assertion\n"
"  358 | static_assert(rst::util::OffsetOf(&GlobalContext::field_C4C8) == 0xC4C8);\n"
```
This PR is to change them over to regular `offsetof` calls. It does compile. but there are loads of more warnings during the compilation. I guess having it successfully compile is better than having no warnings, right?

2021-07-30 23:02 UTC, leoetlino requested changes

2021-07-30 23:02 UTC, leoetlino commented on source/common/utils.h
> +// template <typename T1, typename T2>
Could you remove this entirely?

2021-07-30 23:02 UTC, leoetlino commented on source/game/actor.h
> +static_assert(offsetof(Actor, field_80) == 0x80);
needs an `#include <cstddef>`  (ditto below)

2021-07-30 23:03 UTC, leoetlino commented
If you can, please squash the commit history. The first 12 commits shouldn't show up in the history ^^

2021-08-04 17:51 UTC, PhlexPlexico commented
Was away for break here, but I hope this is okay now 😬  I don't really do squashes very often so this was definitely a good experience for me, lemme know if anything else is needed!

2021-08-04 18:21 UTC, leoetlino approved these changes
Thanks for fixing this!

2021-08-04 18:21 UTC, merged